"""Add pages_content column to papers, papers_staging table

Revision ID: 787670bc8470
Revises: c1cf20366dd8
Create Date: 2026-02-27 22:57:44.946781

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '787670bc8470'
down_revision = 'c1cf20366dd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('pages_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='cr_soles')
    op.add_column('papers_staging', sa.Column('pages_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='cr_soles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers_staging', 'pages_content', schema='cr_soles')
    op.drop_column('papers', 'pages_content', schema='cr_soles')
    # ### end Alembic commands ###
